site_name: Carrent Elias
site_url: ""

nav:
  - Home: index.md
  - C4 Pattern: c4Patter.md
  - Use Cases: UseCases.md
  - Verschiedene Views (4+1): fourdifferentviews.md
  - Qualitätsbaum für NFR: qualitätsbaum.md
  - Teststrategie / -planung: testStrategieUndMetrik.md

theme: readthedocs